# Numpy

In [1]:
import numpy as np

# Creation of 1d and 2d Array

In [2]:
mylist1 = [22,33,44,55,66]

n5 = np.array(mylist1)
print(n5)
print(type(n5))
print()
print(n5.ndim)
print(n5.shape)
print()
print(n5.size)  ##  total number of elements in the array
print()
print(n5.itemsize)  ## mem in bytes, occupied by each element/item
print(n5.dtype)
print()
print("total_mem_occupied {} bytes".format(n5.size * n5.itemsize))

[22 33 44 55 66]
<class 'numpy.ndarray'>

1
(5,)

5

4
int32

total_mem_occupied 20 bytes


In [4]:
mylist43 = [ [11,22,33], [44,55,66], [77,88,99], [123,456,789]  ]   ##  4x3 list

n43 = np.array(mylist43)
print(n43)
print(type(n43))
print()
print(n43.ndim)
print(n43.shape)
print()
print(n43.size)  ##  total number of elements in the array
print()
print(n43.itemsize)  ## mem in bytes, occupied by each element/item
print(n43.dtype)
print()
print("total_mem_occupied {} bytes".format(n43.size * n43.itemsize))

[[ 11  22  33]
 [ 44  55  66]
 [ 77  88  99]
 [123 456 789]]
<class 'numpy.ndarray'>

2
(4, 3)

12

4
int32

total_mem_occupied 48 bytes


In [6]:
mylist43 = [ [11,22,33], [44,55.5,66], [77,88,99], [123,456,789]  ]   ##  4x3 list

n43 = np.array(mylist43)
print(n43)
print(n43.size)  ##  total number of elements in the array
print(n43.itemsize)  ## mem in bytes, occupied by each element/item
print(n43.dtype)
print("total_mem_occupied {} bytes".format(n43.size * n43.itemsize))

[[ 11.   22.   33. ]
 [ 44.   55.5  66. ]
 [ 77.   88.   99. ]
 [123.  456.  789. ]]
12
8
float64
total_mem_occupied 96 bytes


In [ ]:
mylist43 = [ [11,22,33], [44,55.5,66], [77,88,99], [123,456,67899]  ]   ##  4x3 list

n43 = np.array(mylist43,dtype=np.int16)  ##  allow dtype to be dynamically calculated
print(n43)
print(n43.size)  ##  total number of elements in the array
print(n43.itemsize)  ## mem in bytes, occupied by each element/item
print(n43.dtype)
print("total_mem_occupied {} bytes".format(n43.size * n43.itemsize))
print('we have lost precision in this example')

In [ ]:
n = np.arange(1,11)
print(n)
print(n.shape)

In [ ]:
n = np.arange(1.5,11.5, 2)
print(n)
print(n.shape)

In [ ]:
n = np.arange(1.5,11.6, 2)
print(n)
print(n.shape)

In [ ]:
n34 = np.arange(12).reshape(3,4)
print(n34)
print(n34.shape)

In [ ]:
n34 = np.arange(12).reshape(3,3)
print(n34)
print(n34.shape)

In [ ]:
n34 = np.arange(12).reshape(4,3)
print(n34)
print(n34.shape)

In [ ]:
print(np.arange(12))
n34 = np.arange(12).reshape(1,12)
print(n34)
print(n34.shape)

In [ ]:
print(np.arange(12))
n34 = np.arange(12).reshape(12,1)
print(n34)
print(n34.shape)

In [ ]:
n34 = np.arange(12).reshape(0,12)
print(n34)
print(n34.shape)

In [ ]:
n = np.arange(1500).reshapepe(75,-1)
print(n.shape)

In [ ]:
1500/70

In [ ]:
n = np.arange(1500).reshape(-1,-1)
print(n.shape)

In [ ]:
n43

In [ ]:
n43.reshape(6,-1)

In [ ]:
np.random.seed(23)
n64 = np.random.randint(low=10, high=1000, size=(6,4) )
print(n64.shape)
print(n64)

In [ ]:
## prn --- factor of 3 numerics......  seed, low, high .... polynomial equation

In [ ]:
n64 = np.random.randint(low=10, high=1000, size=(6,4) )
print(n64.shape)
print(n64)

# Access

In [93]:
np.random.seed(23)
n79 = np.random.randint(low=10, high=100, size=(7,9))
print(n79)

[[93 50 83 64 41 86 49 35 61]
 [16 55 22 59 76 85 95 79 74]
 [22 31 58 51 89 72 67 29 43]
 [69 49 25 46 75 11 53 25 96]
 [93 68 35 76 84 45 66 23 70]
 [32 48 41 88 10 31 16 42 42]
 [24 41 88 93 90 80 76 92 95]]


In [ ]:
n79[0]

In [ ]:
n79[0,0]

In [ ]:
n79[0,0]

In [ ]:
n79

In [ ]:
n79[-1, 0]

In [ ]:
n79[-1,-1]

In [ ]:
n79[0, -1]

In [ ]:
n79

In [ ]:
n79[1:4]

In [ ]:
n79[2:6, 2:6]

In [ ]:
n79

In [ ]:
n79[ [1,4,-1]  ]

In [ ]:
n79

In [ ]:
n79[ [1,4,5]  , [2,6,7]  ]

In [ ]:
n79

In [ ]:
n79[: , 4]

In [ ]:
n79[: , [4]  ]  

In [ ]:
n79[[1,3,5],[2,5,-1,3]]  ##  error


In [ ]:
n79

In [ ]:
n79[2:5   , [0,3,5,6,-1] ]

In [ ]:
n79

In [ ]:
n79[0,0] = 100

In [ ]:
n79

In [ ]:
n79[2:5] = 0

In [ ]:
n79

In [ ]:
n79[2:5] = 9999

In [94]:
n39 = np.arange(1000,1027).reshape(3,9)
n39

array([[1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
       [1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017],
       [1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026]])

In [95]:
n79

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95]])

In [96]:
n79[2:5] = n39

In [97]:
n79

array([[  93,   50,   83,   64,   41,   86,   49,   35,   61],
       [  16,   55,   22,   59,   76,   85,   95,   79,   74],
       [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
       [1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017],
       [1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026],
       [  32,   48,   41,   88,   10,   31,   16,   42,   42],
       [  24,   41,   88,   93,   90,   80,   76,   92,   95]])

In [ ]:
n5

In [ ]:
n5[0]

In [ ]:
n5[1:4]

In [ ]:
n5[[0,-1,1]] = 999

In [ ]:
n5

In [ ]:
n5[[0,-1,1]] = [666,777,888]

In [ ]:
n5

In [ ]:
np.random.seed(23)
n79 = np.random.randint(low=10, high=100, size=(7,9))
print(n79)

In [ ]:
mask = n79 > 50
print(mask)
print(type(mask))

In [ ]:
n79[mask]

In [ ]:
ng25 = n79[n79>25]
print(ng25)

In [ ]:
n79 > 25

In [ ]:
n79 % 2 == 0

In [ ]:
n79[(n79 > 25)  & (n79 % 2 == 0)]

In [ ]:
n79[(n79 > 25)  | (n79 % 2 == 0)]

In [ ]:
x,y = np.where(n79 > 25)
print(x)
print(y)

In [ ]:
n79

In [ ]:
xy = list(zip(x,y))
print(xy)

In [ ]:
for item in xy:
    print(n79[item])

In [75]:
n79

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95]])

In [76]:
n79[n79>50] = 5555

In [77]:
n79

array([[5555,   50, 5555, 5555,   41, 5555,   49,   35, 5555],
       [  16, 5555,   22, 5555, 5555, 5555, 5555, 5555, 5555],
       [  22,   31, 5555, 5555, 5555, 5555, 5555,   29,   43],
       [5555,   49,   25,   46, 5555,   11, 5555,   25, 5555],
       [5555, 5555,   35, 5555, 5555,   45, 5555,   23, 5555],
       [  32,   48,   41, 5555,   10,   31,   16,   42,   42],
       [  24,   41, 5555, 5555, 5555, 5555, 5555, 5555, 5555]])

# Predefined functions

In [78]:
np.random.seed(23)
n79 = np.random.randint(low=10, high=100, size=(7,9))
print(n79)

[[93 50 83 64 41 86 49 35 61]
 [16 55 22 59 76 85 95 79 74]
 [22 31 58 51 89 72 67 29 43]
 [69 49 25 46 75 11 53 25 96]
 [93 68 35 76 84 45 66 23 70]
 [32 48 41 88 10 31 16 42 42]
 [24 41 88 93 90 80 76 92 95]]


In [79]:
n79.max()

96

In [80]:
n79.max(axis=0)

array([93, 68, 88, 93, 90, 86, 95, 92, 96])

In [81]:
n79.max(axis=1)

array([93, 95, 89, 96, 93, 88, 95])

In [82]:
n79.min()

10

In [83]:
n79.std()

25.305042483803103

In [84]:
n79.var()

640.3451751070799

In [85]:
n79.mean()

57.507936507936506

In [86]:
n79.mean(axis=0)

array([49.85714286, 48.85714286, 50.28571429, 68.14285714, 66.42857143,
       58.57142857, 60.28571429, 46.42857143, 68.71428571])

In [87]:
n79.mean(axis=1)

array([62.44444444, 62.33333333, 51.33333333, 49.88888889, 62.22222222,
       38.88888889, 75.44444444])

In [88]:
n79.sum()

3623

In [89]:
n79.sum(axis=0)

array([349, 342, 352, 477, 465, 410, 422, 325, 481])

In [90]:
n79

array([[93, 50, 83, 64, 41, 86, 49, 35, 61],
       [16, 55, 22, 59, 76, 85, 95, 79, 74],
       [22, 31, 58, 51, 89, 72, 67, 29, 43],
       [69, 49, 25, 46, 75, 11, 53, 25, 96],
       [93, 68, 35, 76, 84, 45, 66, 23, 70],
       [32, 48, 41, 88, 10, 31, 16, 42, 42],
       [24, 41, 88, 93, 90, 80, 76, 92, 95]])

In [92]:
np.median(n79)

58.0