In [1]:
print ("My name is","Tulika","Sinha")   #performs cncatenation

My name is Tulika Sinha


In [2]:
print("My name is"+"Tulika Sinha") # This syntax performs concatenation using print function

My name isTulika Sinha


In [3]:
value="Tulika"
count=3
result=value*count
print(result)

TulikaTulikaTulika


In [4]:
total_cost=2000
quantity =3
price_per_quantity=total_cost*quantity
print(price_per_quantity)

6000


In [1]:
d = {860: 'python', 109: 'java', 12: 'selenium'}

for i in d:

    print(i)

860
109
12


In [1]:
a,b,c=10,20,30
print(a)
print(b)
print(c)

10
20
30


In [2]:
a=b=c=4
print(a)
print(b)
print(c)

4
4
4


In [6]:
def suming(num1,num2,num3):
    print(num1,num2,num3)
    return num1+num2+num3


In [7]:
x = suming(10,20,30)
print(x)

10 20 30
60


In [8]:
def func(p1,p2):
    print(p1,p2)

In [9]:
x=func(10,20)
print(x)

10 20
None


In [13]:
def checkNumber(number):
    if number%2 == 0:
        return True
    else:
        return False

In [15]:
x=checkNumber(10)
print(x)

True


In [19]:
def tempFeel(temp):
    if temp > 90:
        return "it is hot"
    elif temp < 60:
        return "it is cold"
    elif temp >= 61 and temp <= 99:
        return "it is just right"

In [21]:
x = int(input("enter temperature : "))
y = tempFeel(x)
print(y)

enter temperature : 59
it is cold


In [22]:
def mf(p0,p1):
    print(p0,p1)

In [24]:
mf(100,200)   # Positional Parameter

100 200


In [25]:
mf(100)

TypeError: mf() missing 1 required positional argument: 'p1'

In [26]:
mf(p1=100)

TypeError: mf() missing 1 required positional argument: 'p0'

In [27]:
mf(p0=10,p1=10)

10 10


In [28]:
mf(10,p1=20)

10 20


In [29]:
mf(p0=0)

TypeError: mf() missing 1 required positional argument: 'p1'

In [30]:
mf(p0=9,1)

SyntaxError: positional argument follows keyword argument (<ipython-input-30-1c565f3ce406>, line 1)

In [31]:
mf(p1=10,p0=9)

9 10


In [32]:
mf(9,p0=0)

TypeError: mf() got multiple values for argument 'p0'

In [33]:
mf(p1=10,p1=20)

SyntaxError: keyword argument repeated (<ipython-input-33-a827e798ce20>, line 1)

In [34]:
mf(p0=9,10)

SyntaxError: positional argument follows keyword argument (<ipython-input-34-f86e90df7c5e>, line 1)

In [35]:
mf(88,88,9)

TypeError: mf() takes 2 positional arguments but 3 were given

In [36]:
def mf(**kwargs):
    print(kwargs)
    print(type(kwargs))

In [37]:
mf(a=10,b=9,c=10)

{'a': 10, 'b': 9, 'c': 10}
<class 'dict'>


In [38]:
mf(x=10,y=99)

{'x': 10, 'y': 99}
<class 'dict'>


In [3]:
isEven = lambda num : num % 2 == 0

In [5]:
isEven(21)

False

In [6]:
Iseven= lambda x: "Yes it is even" if x%2==0 else "No its not even"

In [7]:
Iseven(20)

'Yes it is even'

In [10]:
cmList = [10,20,30,40]
fcm2m = lambda c : c*10

cm2mList = map(fcm2m,cmList)  # named function object
print(list(cm2mList))

[100, 200, 300, 400]


In [13]:
cm_list=[10,20,30]  
mm_list=list(map(lambda x:x*10,cm_list))  #Anonymous function object
mm_list

[100, 200, 300]

In [16]:
clist=[36,37,38,39]
#c2f=(c*9)/5 +32

flist= map(lambda k : (k*9)/5 +32,clist)
print(list(flist))

[96.8, 98.6, 100.4, 102.2]


In [18]:
mmarks=[33,34]
pmarks = [44,45,66]

tmarks=map(lambda m,p:m+p,mmarks,pmarks)
print(list(tmarks))

[77, 79]


In [20]:
import random

for n in range(1,10):
    r=random.randint(10,100)
    print(r)

59
28
100
19
78
12
80
94
80


In [22]:
rList={n:random.randint(10,100)   for n in range(30)}
print(rList)

{0: 19, 1: 38, 2: 34, 3: 37, 4: 68, 5: 38, 6: 48, 7: 47, 8: 21, 9: 24, 10: 74, 11: 30, 12: 59, 13: 14, 14: 37, 15: 34, 16: 86, 17: 21, 18: 94, 19: 94, 20: 54, 21: 96, 22: 49, 23: 89, 24: 76, 25: 78, 26: 39, 27: 12, 28: 79, 29: 60}


In [23]:
def isPrime(num):
    if num < 2:
        return False
    
    for divisor in range(2,num):
        if num % divisor == 0:
            return False
        
    return True

In [26]:
primeList=filter(lambda num : isPrime(num),rList)   #Returns only prime numbers within the list -- Filters the required one
print(list(primeList))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [27]:
pnums1=filter(isPrime,rList) 
print(list(pnums1))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [30]:
from functools import reduce
rMax=reduce(lambda x,y:x if x>y else y,rList)
print(rMax)

29


In [31]:
import itertools

In [35]:
nList1 = [1,2,4,5,6]

rList = list(itertools.accumulate(nList1,lambda x,y:x+y))
print(rList)

'''
X   y  X+Y
1   2   3
3   4   7
7   5   12
12  6  18
'''
print()

[1, 3, 7, 12, 18]



In [2]:
import numpy as np    #Alias

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [23]:
mylist43 = [[11,22,33],[44,55,66],[77,88,99],[123,456,789]]
  #4*3 list

In [24]:
narr = np.array(mylist43)
print(narr)
print(narr.size)
print(narr.ndim)
print(narr.itemsize)
print(narr.dtype)

[[ 11  22  33]
 [ 44  55  66]
 [ 77  88  99]
 [123 456 789]]
12
2
4
int32


In [25]:
print(np.array(mylist43))

[[ 11  22  33]
 [ 44  55  66]
 [ 77  88  99]
 [123 456 789]]


In [1]:
np.random.seed(23)
n79=np.arange()

NameError: name 'np' is not defined

In [2]:
def func(): 

    print("You are welcome to func") 

    print(var) 

func()

You are welcome to func


NameError: name 'var' is not defined

In [4]:
import math
def squareroot(a):
       return math.sqrt(a)

In [5]:
squareroot(4)

2.0

In [9]:
def great(string):
        name=string
        if name=='string':
             print("its great")
great(123)

In [11]:
mt1 = ('Bank', 'City', 'Branch')
mt2 = ('SBI', 'Blr')
z = zip(mt1,mt2)   ## zip return an o/p, which can be consumed only once. it is called ITERATOR.. temporary one time readable container of values
print(type(z))
print(z)
print(list(z))

<class 'zip'>
[('Bank', 'SBI'), ('City', 'Blr')]


In [1]:
import pandas as pd

In [2]:
md1 = {'Rev' : [100,200,300],'Exp' : [10,20,30]}
pd.DataFrame(md1)

Rev  Exp
0  100   10
1  200   20
2  300   30

In [3]:
myList = ['Tata','Birla','TCS']
md1 = {'Rev' : [100,200,300],'Exp' : [10,20,30]}
pd.DataFrame(md1,index=myList)

Rev  Exp
Tata   100   10
Birla  200   20
TCS    300   30

AttributeError: 'dict' object has no attribute 'indexes'