In [3]:
import numpy as np

a=np.random.randn(1,1)

a

array([[0.30373874]])

In [4]:
np.random.randint(1,0)

ValueError: low >= high

In [5]:
import numpy as np

a=np.arange(10)

a[::2]

array([0, 2, 4, 6, 8])

In [6]:
import numpy as np

a = np.array([1,2,3,4,5])

b = np.arange(0,10,2)

c = a + b

print (c[4])

13


In [7]:
import numpy as np

a=np.arange(15).reshape(3,5)

print(a.size)

15


In [8]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
import numpy as np

a=np.arange(1,5,20j)

a

array([], dtype=complex128)

In [10]:
def num(*args):
    return enumerate(*args)
list(num(('123')))

[(0, '1'), (1, '2'), (2, '3')]

In [11]:
def num(*kwargs):
    return enumerate(*kwargs)
list(num(('123')))

[(0, '1'), (1, '2'), (2, '3')]

In [12]:
def sqrt(num):
    num=0
    import math
    return math.sqrt(num)
sqrt(9)

0.0

In [14]:
def great(string):
    name=string
    if name=='string':
        print("its great")
great(123)

In [15]:
elements = [100,200,200]
def up(x):
    return x+1
print(list(map(elements, up)))

TypeError: 'function' object is not iterable

In [16]:
def code():
    for numbers in '1234':
        for letters in 'abc':
            print(len(nubers),len(letters))
code().sum()

NameError: name 'nubers' is not defined

In [17]:
def radian(num):
    num=num
    import math
    return math.radian(num)
radian(9)

AttributeError: module 'math' has no attribute 'radian'

In [18]:
def radian(num):
    num=num
    import math
    return math.isnan(num)
radian(9)

False

In [19]:
def codenum():
for numbers in '1234':
if numbers==4:
print(“zero”)
else:
pass

IndentationError: expected an indented block (<ipython-input-19-7e55f2c234c7>, line 2)

In [20]:
def code():
    for numbers in '1234':
        for letters in 'abc':
            print(len(nubers),len(letters))
code()

NameError: name 'nubers' is not defined

In [21]:
count = 15
def some_method():
    global count
    count = count + 5
    print(count)
some_method()

20


In [27]:
def codenum():
    for numbers in '1234':
        if numbers==0:
            print("zero")
        else:
            pass

In [28]:
elements = [100,200,200]
def up(x):
    return x+1
print(list(map(elements, up)))

TypeError: 'function' object is not iterable

In [1]:
bin(56)

'0b111000'

In [27]:
a=[10,12,11,16,71,12,9,56,9]

In [28]:
a

[10, 12, 11, 16, 71, 12, 9, 56, 9]

In [29]:
a.sort() #By default ascending order
a

[9, 9, 10, 11, 12, 12, 16, 56, 71]

In [12]:
a.sort(reverse=True) #Descending order

In [13]:
a

[71, 56, 16, 12, 12, 11, 10, 9]

In [14]:
b=[11,16,2,34,21,11,8,18]

In [15]:
sorted(b)

[2, 8, 11, 11, 16, 18, 21, 34]

In [16]:
b

[11, 16, 2, 34, 21, 11, 8, 18]

In [17]:
len(a)

8

In [18]:
min(a)

9

In [19]:
max(a)

71

In [20]:
a.append(12)

In [21]:
a

[71, 56, 16, 12, 12, 11, 10, 9, 12]

In [22]:
a.pop()

12

In [23]:
a.clear()

In [24]:
a

[]

In [25]:
c=a.copy()

In [26]:
c

[]

In [30]:
a.count(9)

2

In [31]:
a.index(9)

0

In [32]:
a.insert(1,89)

In [33]:
a

[9, 89, 9, 10, 11, 12, 12, 16, 56, 71]

In [34]:
a.pop(4)

11

In [35]:
a

[9, 89, 9, 10, 12, 12, 16, 56, 71]

In [36]:
a.reverse()

In [37]:
a

[71, 56, 16, 12, 12, 10, 9, 89, 9]

In [38]:
a.sort()

In [39]:
a

[9, 9, 10, 12, 12, 16, 56, 71, 89]

In [40]:
p=(2,11,5,9,3)

In [41]:
p

(2, 11, 5, 9, 3)

In [42]:
p.sort()

AttributeError: 'tuple' object has no attribute 'sort'

In [44]:
sorted(p,reverse=True)

[11, 9, 5, 3, 2]

In [46]:
def addition(*args):
    return bin(args)
addition(10,10)

TypeError: 'tuple' object cannot be interpreted as an integer

In [47]:
def func():
    print("You are welcome to func")
    print(var)
func()

You are welcome to func


NameError: name 'var' is not defined

In [48]:
def square(*args):
    return bin(sum(*args))
square((1,2,3))

'0b110'

In [49]:
def num(*kwargs):
    return enumerate(*kwargs)
list(num(('123')))

[(0, '1'), (1, '2'), (2, '3')]

In [52]:
import math

In [54]:
def squareroot(a):
    return math.sqrt(a)

In [55]:
squareroot(9)

3.0

In [58]:
def addition(*args):
    return bin(args)
addition(10,10)

TypeError: 'tuple' object cannot be interpreted as an integer

In [60]:
def codenum():
    for numbers in '1234':
        if numbers==0:
            print("zero")
        else:
            pass

SyntaxError: invalid character in identifier (<ipython-input-60-b866d40f971e>, line 5)

In [74]:
def codenum():
    for numbers in '1234':
        if numbers==0:
            print("zero")
        else:
            pass

In [75]:
codenum()

In [68]:
def code():
    for numbers in '1234':
        for letters in 'abc':
            print(len(nubers),len(letters))
code()

NameError: name 'nubers' is not defined

In [70]:
elements = [100,200,200]
def up(x):
    return x+1
print(list(map(elements, up)))

TypeError: 'function' object is not iterable

In [73]:
def great(string):
    name=string
    if name=='string':
        print("its great")
great(123)

In [76]:
import seaborn as sns

NameError: name 'df' is not defined